### ISSUE TITLE
Reset Table sorted columns

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-compose#121]
Now tables have a hidden sorting "ordered children", but it's impossible to go back to this state once we sort the table by column. 
Two possible solutions:
1) remove all together the column sorting feature and use a dropdown (top right corner).
2) add a "reset sorting" button which will default to the folder ordering.

The first solution is the most elegant but we won't use the material ui table's sorting anymore. In that case would using another table (with the move feature included) better?

The second solution is the most straight-forward one, which involves less changes.

**Comment by abdallah75** [comment]
This will be added with the new table (see issue #152 )
