### ISSUE TITLE
Trim item name on add and edit

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-compose#153]
`"my name "` does not pass the regex validation for item name.

**Comment by Julien-Torrent** [comment]
Should the trimming be done on the frontend only ?

I've talked with André, he thinks it's better to have the frontend to do the trimming.

- There is no extra logic to add on the backend
- This allows to be sure that the data coming in the server is correctly formatted
- Less risk to have bad data stored in the database

**Comment by Julien-Torrent** [comment]
The trimming will be done in the cache and when the query is sent to the server.

**Comment by Julien-Torrent** [comment]
Implemented in [grasp-compose#53](https://github.com/graasp/graasp-query-client/pull/53)
