### ISSUE TITLE
formula box is sometimes outside the screen

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-compose#160]
Formula box is sometimes outside the screen.

![image](https://user-images.githubusercontent.com/1707188/125610471-ba5bf06e-2ca3-4d40-8d5a-1ce9d071d32e.png)

**Comment by juancarlosfarah** [comment]
@pyphilia, feel free to reassign if necessary. Also, does this fix maybe belong in `graasp-ui`?

**Comment by pyphilia** [comment]
Yes the fix will take place in graasp-ui. I'll let this issue here until someone takes it. 
Also, this might be fixed while solving this issue https://github.com/graasp/graasp-compose/issues/74

**Comment by pyphilia** [comment]
This have been automatically fixed in https://github.com/graasp/graasp-compose/pull/137 right @abdallah75 ?

**Comment by abdallah75** [comment]
Yes it should be fixed with the new add item layout
