### ISSUE TITLE
Fix yarn crashes on install on Github Actions

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-compose#170]
Yarn will randomly fail with filesystem errors (e.g. `ENOENT`) on the `install` step, errors seem to stem from cache problems and disk concurrency issues (see https://github.com/yarnpkg/yarn/issues/2629)

Example crash:
```
error https://registry.yarnpkg.com/functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "EEXIST: file already exists, mkdir '/home/runner/.cache/yarn/v6/npm-functional-red-black-tree-1.0.1-1b0ab3bd553b2a0d6399d29c0e3ea0b252078327-integrity/node_modules/functional-red-black-tree'"
```

Recommended action is to use yarn >= v2 (see https://yarnpkg.com/getting-started/migration) as caching should be improved.

Currently Actions runs on `ubuntu-latest` (btw where does it get yarn from?) and `yarn` 1.22.10. Find a way to upgrade yarn workflow.

We may want to use the `setup-node` workflow: https://github.com/actions/setup-node
Example with cypress https://github.com/marketplace/actions/cypress-io#custom-cache-key

Could be applied to other repos as well

**Comment by pyphilia** [comment]
Thanks for this issue! Would be great to get it solve asap.
This link to migrate form yarn v1 to v2 might come handful https://next.yarnpkg.com/getting-started/migration
