### ISSUE TITLE
add an emoji picker to text editor

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-compose#452]
It would be great if the text editor had an emoji-picker.

**Comment by Duri01** [comment]
Hello, it is still actuall ? Thanks

**Comment by pyphilia** [comment]
Hello @Duri01 , yes it is still open, but the changes will have to happen in this repo https://github.com/graasp/graasp-ui let me know if you're interested I can move this issue.

**Comment by pyphilia** [comment]
Move this issue to https://github.com/graasp/graasp-ui/issues/166

**Comment by pyphilia** [comment]
@Duri01 I cannot assign you on the other issue, you can maybe leave a comment over there?
